services:
  manager_bot:
    build: .
    container_name: manager_bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.json:/config.json:ro
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
